Otchet№3
Art23urDav/Laba1 pull request #3
Opened 2023-10-27 05:22 UTC by Art23urDav

2023-10-28 07:36 UTC, lamer0k requested changes

2023-10-28 07:36 UTC, lamer0k commented on Otchets3.adoc
> +Для разыменования указателя нужно записать в переменную, хранящую значение адреса какой-то другой переменной, любое число.
Что то непонятное написано, как сделать разыменование указателя?

2023-10-28 07:36 UTC, lamer0k commented on Otchets3.adoc
> +Указатели можно складывать, вычитать, сравнивать. Но указатели должны быть одного типа. Т.е. не нужно например складывать укатель типа char * и int *.
можно складывать, но смысла в этом нет. Другое дело, что можно складывать с целым и вычитать с целым.

2023-10-28 07:36 UTC, lamer0k commented on Otchets3.adoc
> +Разберем пример сложения указателей:
как раз пример складывания указателя с целым.

2023-10-28 07:37 UTC, lamer0k commented on Otchets3.adoc
> +image::picture\Процесс сложения указателей.png[]
картинка не видна

2023-10-28 07:37 UTC, lamer0k commented on Otchets3.adoc
> +image::picture\Значение указателя в памяти.png[]
картинка не видна

2023-11-05 11:59 UTC, Art23urDav commented on Otchets3.adoc
> +Для разыменования указателя нужно записать в переменную, хранящую значение адреса какой-то другой переменной, любое число.
Исправил

2023-11-05 12:00 UTC, Art23urDav commented on Otchets3.adoc
> +Указатели можно складывать, вычитать, сравнивать. Но указатели должны быть одного типа. Т.е. не нужно например складывать укатель типа char * и int *.
Исправил

2023-11-05 12:00 UTC, Art23urDav commented on Otchets3.adoc
> +Разберем пример сложения указателей:
Исправил

2023-11-05 12:00 UTC, Art23urDav commented on Otchets3.adoc
> +image::picture\Процесс сложения указателей.png[]
Исправил

2023-11-05 12:00 UTC, Art23urDav commented on Otchets3.adoc
> +image::picture\Значение указателя в памяти.png[]
Исправил

2023-11-11 09:17 UTC, lamer0k commented on Otchets3.adoc
> +Указатели можно складывать, вычитать, сравнивать. Но указатели должны быть одного типа. Т.е. не нужно например складывать укатель типа char * и int *.
В общем и целом - некоторые компиляторы позволяют складывать, но это неправильно, по хорошему указатели складывать нельзя, потому что это бесмыслено. Но можно вычитать, например, чтобы найти количество байт между двумя указателями.

2023-11-11 09:18 UTC, lamer0k reviewed
один коммент

2023-12-16 09:34 UTC, lamer0k approved these changes

2023-12-23 09:04 UTC, merged